declare module 'styled-components/native'
declare module 'react-native-web'
declare module '@react-navigation/web'
declare module 'react-navigation-stack-web'
declare module 'react-native-datepicker-dialog'
declare module 'redux-saga/effects'
declare module 'redux-saga'
declare module 'lodash.throttle'